Coffee_web/Coffee_web/Controllers/AddCustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Coffee_web.Models;
namespace Coffee_web.Controllers
{
    public class AddCustomerController : Controller
    {
        CoffeeEntities db = new CoffeeEntities();
        // GET: AddCustomer
        public ActionResult AddCus()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCus(Customer _customer)
        {
            if (ModelState.IsValid)
            {
                var check = db.Customers.FirstOrDefault(s=>s.id_customer == _customer.id_customer);
                if (check == null)
                {
                    db.Customers.Add(_customer);
                    db.SaveChanges();
                    return RedirectToAction("Show", "ShoppingCart");
                }
                else
                {
                    ViewBag.error = "Da trung id";
                    return View();
                }
            }
            return View();
        }
    }
}

Coffee_web/Coffee_web/Views/AddCustomer/AddCus.cshtml
@model Coffee_web.Models.Customer

@{
    ViewBag.Title = "AddCus";
    Layout = "~/Views/Shared/_LayoutCreate.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.bundle.min.js"></script>
<style>
    div{
        text-align:center;
        align-items:center;
    }
    table tr td{
        text-align:center;
        margin:0 auto;
        
    }

    table{
        margin:auto;
    }
</style>
@using (Html.BeginForm("AddCus", "AddCustomer", FormMethod.Post))
{
    <h2>AddCus</h2>
    <div>
        <table>
            <tr>
                <td>ID:</td>
                <td>@Html.TextBoxFor(m => m.id_customer)</td>
                <td>
                    @Html.ValidationMessageFor(m => m.id_customer)
                    @if (ViewBag.error != null)
                    {
                        <h5>@ViewBag.error</h5>
                    }
                </td>
            </tr>
            <tr>
                <td>Number:</td>
                <td>@Html.TextBoxFor(m => m.number_phone)</td>
                <td>@Html.ValidationMessageFor(m => m.number_phone)</td>
            </tr>
            <tr>
                <td>Email:</td>
                <td>@Html.TextBoxFor(m => m.email)</td>
                <td>@Html.ValidationMessageFor(m => m.email)</td>
            </tr>
            <tr>
                <td colspan="4">
                    <input type="submit" value="Dang ky" class="btn btn-success" onclick=" return  confirm('Register successfull...') " />
                </td>

            </tr>
        </table>
    </div>
}

<div>
    <button onclick="goBack()" class="btn btn-primary">Back to ProductClient</button>
</div>

<script>
    function goBack() {
        window.location.href = '@Url.Action("Show", "ShoppingCart")';
    }
</script>