Coffee_web/Coffee_web/Controllers/CatogoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Coffee_web.Models;

namespace CoffeeManager.Controllers
{
    public class CatogoryController : Controller
    {
        CoffeeEntities database = new CoffeeEntities();
        // GET: Catogory
        public ActionResult Index()
        {
            var list = database.Catogories.ToList();
            ViewBag.listCatogory = list;
            return PartialView(list);
        }
    }
}

Coffee_web/Coffee_web/Controllers/CoffeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnWebCF.Controllers
{
    public class CoffeeController : Controller
    {
        // GET: Coffee
        public ActionResult LayoutMain()
        {
            return View();
        }
    }
}

Coffee_web/Coffee_web/Controllers/StoragesController.cs
using Coffee_web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Coffee_web.Controllers
{
    public class StoragesController : Controller
    {
        CoffeeEntities db = new CoffeeEntities();
        // GET: Storages
        public ActionResult StoragesMain()
        {
            List<Product> products = db.Products.ToList();
         
            List<Storages> list= products.Select(
                x=>new Storages()
                {
                    images=x.Images,
                    ProductID = x.id_product,
                    ProductName = x.name_product,
                    Num = x.num
                }
                ).ToList();
            return View(list);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Product product)
        {
            db.Products.Add(product);
            db.SaveChanges();
            return RedirectToAction("StoragesMain");
        }

        public ActionResult Edit(int id)
        {
            return View(db.Products.Where(s=> s.id_product == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Edit(int id,Product pro)
        {
            db.Entry(pro).State=System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("StoragesMain");
        }
        public ActionResult Delete(int id)
        {
            return View(db.Products.Where(s=>s.id_product == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Delete(int id,Product product)
        {
            product = db.Products.Where(s => s.id_product == id).FirstOrDefault();
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("StoragesMain");
        }
        public ActionResult Details(int id)
        {
            return View(db.Products.Where(s => s.id_product == id).FirstOrDefault()) ;
        }
    }
}

Coffee_web/Coffee_web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Coffee_web/Coffee_web/Views/Shared/_LayoutCreate.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        /*body {
            background-image: url('../../content/img/—pngtree—cafe poster background_416615.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }*/
        body, html {
            margin: 0;
            padding: 0;
        }

        .div-top {
            margin: 0;
            padding: 0;
        }

        .main-content {
            display: flex;
            flex-wrap: wrap;
        }

        .div-top {
            width: 100%;
            height: 50px;
            margin-bottom: 10px;
        }

        .div-content {
            width: 100%;
            height: 500px;
            float: left;
            margin-top: 50px;
        }

        .div-footer {
            width: 100%;
            height: 100px;
        }

        .nav-link:hover {
            text-decoration: none;
            color: orangered;
        }

        .nav-link {
            font-size: 20px;
            font-family: 'Roboto Slab', serif;
            color: white;
        }
    </style>
</head>
<body>
    <div class="div-top">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#" style="font-size: 35px; font-family: 'Roboto Slab', serif;">Coffee Chill With Friends</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "ProductClient")">Trang Chủ</a>

                        </li>
                    </ul>
                    <ul class="navbar-nav navbar-right">
                        <li>
                            <img src="@Url.Content("~/Content/Img/icons8-buy-50.png")" style="height:46px;width:46px" />
                            @Html.Action("BagCart", "ShoppingCart")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="main-content">
        <div class="div-left">
        </div>
        <div class="div-content">
            @RenderBody()
        </div>
    </div>
    <div class="div-footer"></div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

Coffee_web/Coffee_web/Views/Shared/_LayoutManager.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <style>
        .dropdown-menu:hover .dropdown-content {
            display: block;
            position: absolute;
        }
    </style>
</head>
<body>
    <div class="nav">
        <p >
            <i class="bi bi-cup-hot-fill" style="color:white"></i> 
            <a id="Name" style="color:white">Coffee Chill With Friends </a>
        </p>
        <div id="Manager">
            <div id="Name_manager">
                @if (Session["name_staff"] != null)
            {
                    <h5>@Session["name_staff"]</h5>
            } 
                <a href="Index" style="color:white;">
                    <i class="bi bi-person-circle" style="cursor:pointer"></i>
                </a>        
            </div>          
            <div class="dropdown-menu">
                <i class="bi bi-list" ></i>
                <div class="dropdown-content" style="position:absolute;">
                    <a href="@Url.Action("StoragesMain","Storages")">Hàng tồn</a>
                    <a href="@Url.Action("LayoutMain","Coffee")">Đăng xuất</a>
                </div>
            </div>   
        </div>

    </div>
   
    <div id="box">
        @RenderBody()
    </div>
    <div id="footer" style="color:white;">
        <p>Email:</p>
        <p>HotLine:</p>
        <p>Address:</p>
    </div>
</body>
</html>

Coffee_web/Coffee_web/Views/Shared/_LayoutShow.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        /*body {
            background-image: url('../../content/img/—pngtree—cafe poster background_416615.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }*/
        body, html {
            margin: 0;
            padding: 0;
        }

        .div-top {
            margin: 0;
            padding: 0;
        }
        .main-content {
            display: flex;
            flex-wrap: wrap;
        }

        .div-top {
            width: 100%;
            height: 50px;
            margin-bottom: 10px;
        }

        .div-content {
            width: 100%;
            height: 500px;
            float: left;
            margin-top:50px;
        }

        .div-footer {
            width: 100%;
            height: 100px;
        }

        .nav-link:hover {
            text-decoration: none;
            color: orangered;
        }

        .nav-link {
            font-size: 20px;
            font-family: 'Roboto Slab', serif;
            color: white;
        }
    </style>
</head>
<body>
    <div class="div-top">
            <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#" style="font-size: 35px; font-family: 'Roboto Slab', serif;">Coffee Chill With Friends</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="collapsibleNavbar">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "ProductClient")">Trang Chủ</a>

                            </li>
                        </ul>
                        <ul class="navbar-nav navbar-right">
                            <li>
                                <img src="@Url.Content("~/Content/Img/icons8-buy-50.png")" style="height:46px;width:46px" />
                                @Html.Action("BagCart", "ShoppingCart")
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
    </div>
        <div class="main-content">
            <div class="div-left">
            </div>
            <div class="div-content">
                @RenderBody()
            </div>
        </div>
        <div class="div-footer"></div>
</body>
</html>

Coffee_web/Coffee_web/Views/Shared/_MasterLayoutProduct.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        body {
            background-image: url('../../content/img/—pngtree—cafe poster background_416615.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }

        .main-content {
            display: flex;
            flex-wrap: wrap;
        }

        .div-top {
            width: 100%;
            height: 50px;
        }

        .div-left {
            margin-top:30px;
            width: 20%;
            height: 500px;
            float: left;
        }

        .div-content {
            width: 80%;
            height: 500px;
            float: left;
            margin-top: 50px;
        }

        .div-footer {
            width: 100%;
            height: 100px;
        }

        .nav-link:hover {
            text-decoration: none;
            color: orangered;
        }

        .nav-link {
            font-size: 20px;
            font-family: 'Roboto Slab', serif;
            color: white;
        }
        #collapsibleNavbar{
            display:flex;
            justify-content:space-between;
        }
    </style>
</head>
<body>
    <div class="div-top">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="container-fluid">
               
                <a class="navbar-brand" href="#" style="font-size: 35px; font-family: 'Roboto Slab', serif;">Coffee Chill With Friends </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Manager", "Home")">Xem doanh thu</a>
                        </li>
                    </ul>
                    <ul class="img" >
                        <li>
                            <img src="@Url.Content("~/Content/Img/icons8-buy-50.png")" style="height:46px;width:46px ; right:0;" />
                            @Html.Action("BagCart","ShoppingCart")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="main-content">
        <div class="div-left">
            @{Html.RenderAction("Index", "Catogory");}   
        </div>
        <div class="div-content">
            @RenderBody()
        </div>
    </div>
    <div class="div-footer"></div>
</body>
</html>